//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Usuario = new HashSet<Usuario>();
            this.Importacao = new HashSet<Importacao>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public System.DateTime dataNascimento { get; set; }
        public string email { get; set; }
        public string foneResidencial { get; set; }
        public string foneCelular { get; set; }
        public string cep { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string bairro { get; set; }
        public string carteiraTrabalho { get; set; }
        public string serieCarteira { get; set; }
        public Nullable<System.DateTime> dataEmissao { get; set; }
        public string cpf { get; set; }
        public string rg { get; set; }
        public Nullable<System.DateTime> dataEmissaoRg { get; set; }
        public string orgaoExpeditor { get; set; }
        public string numeroPis { get; set; }
        public Nullable<System.DateTime> dataCadastro { get; set; }
        public string banco { get; set; }
        public string agencia { get; set; }
        public string codigoBanco { get; set; }
        public string codigoAgencia { get; set; }
        public string endereco { get; set; }
        public int idEscolaridade { get; set; }
        public int idCidade { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<int> idFuncao { get; set; }
        public Nullable<int> idJornada { get; set; }
        public Nullable<int> idEstadoCTPS { get; set; }
        public Nullable<int> idEstadoRG { get; set; }
        public Nullable<int> idCidadePIS { get; set; }
        public string sexo { get; set; }
        public string foto { get; set; }
        public Nullable<int> idbanco { get; set; }
    
        public virtual Cidade Cidade { get; set; }
        public virtual Cidade CidadePIS { get; set; }
        public virtual Departamento Departamento { get; set; }
        public virtual Escolaridade Escolaridade { get; set; }
        public virtual Estado EstadoRG { get; set; }
        public virtual Funcao_Cargo Funcao_Cargo { get; set; }
        public virtual Jornada Jornada { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Usuario> Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Importacao> Importacao { get; set; }
        public virtual Banco Banco1 { get; set; }
    }
}
