//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Importacao
    {
        public int IDEntrada { get; set; }
        public int IDFuncionario { get; set; }
        public System.DateTime data { get; set; }
        public System.TimeSpan hora { get; set; }
        public string nsr { get; set; }
        public string numfabrep { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
