//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class registro_pontoEntities : DbContext
    {
        public registro_pontoEntities()
            : base("name=registro_pontoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Escolaridade> Escolaridade { get; set; }
        public virtual DbSet<Jornada> Jornada { get; set; }
        public virtual DbSet<TipoAbono> TipoAbono { get; set; }
        public virtual DbSet<Funcao_Cargo> Funcao_Cargo { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<Cidade> Cidade { get; set; }
        public virtual DbSet<Estado> Estado { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Importacao> Importacao { get; set; }
        public virtual DbSet<Banco> Banco { get; set; }
    }
}
