//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int Id { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
        public byte[] email { get; set; }
        public byte[] data { get; set; }
        public int IdFuncionario { get; set; }
    
        public virtual Funcionario Funcionario { get; set; }
    }
}
